name: Publish package to GitHub Packages
on:
  push:
    tags:
      - v**-SNAPSHOT
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version:
          - 2.4
          - 3.1
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --projects arangodb-spark-datasource-${{matrix.spark-version}} --also-make -Pspark-${{matrix.spark-version}} -Dgpg.skip=true -DskipTests=true --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
