name: Python CI

on:
  push:
    branches:
      - main
      - devel
      - test/pyspark
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - devel

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        scala-version: [2.12]
        spark-version: [3.1]
        topology: [single]
        java-version: [11]
        docker-img: ["docker.io/arangodb/arangodb:3.9.1"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
      - uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          STARTER_MODE: ${{matrix.topology}}
          DOCKER_IMAGE: ${{matrix.docker-img}}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Maven Info
        run: mvn -version
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyspark~=${{matrix.spark-version}}.0
          pip install -r python-integration-tests/test-requirements.txt
      - name: Build Spark Datasource Artifact
        run: |
          mvn -e --no-transfer-progress -DskipTests -Pscala-${{matrix.scala-version}} -Pspark-${{matrix.spark-version}} package
          find . -name "arangodb-spark-datasource-${{matrix.spark-version}}_*-jar-with-dependencies.jar" -exec cp {} ./arangodb-spark-datasource-under-test.jar \;
      - name: Run tests for PySpark ${{matrix.spark-version}} on Python ${{matrix.python-version}}
        run: |
          pytest python-integration-tests/integration --adb-datasource-jar ./arangodb-spark-datasource-under-test.jar --adb-hostname 172.28.0.1
