name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - devel
    paths-ignore:
      - '.github/**'
      - 'bin/**'
      - 'demo/**'
      - 'docker/**'
      - 'lib/**'
      - 'python-integration-tests/**'
      - 'ChangeLog.md'
      - 'dev-README.md'
      - 'README.md'
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - devel

jobs:

## FIXME: sonar plugin requires Java 17
#  sonar:
#    timeout-minutes: 10
#    runs-on: ubuntu-latest
#
#    strategy:
#      fail-fast: false
#      matrix:
#        scala-version:
#          - 2.12
#        spark-version:
#          - 3.4
#        topology:
#          - single
#        java-version:
#          - 11
#        docker-img:
#          - docker.io/arangodb/arangodb:3.12
#
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - uses: actions/setup-java@v2
#        with:
#          java-version: ${{matrix.java-version}}
#          distribution: 'adopt'
#          cache: maven
#      - name: Start Database
#        run: ./docker/start_db.sh
#        env:
#          STARTER_MODE: ${{matrix.topology}}
#          DOCKER_IMAGE: ${{matrix.docker-img}}
#      - name: Cache SonarCloud packages
#        uses: actions/cache@v2
#        with:
#          path: ~/.sonar/cache
#          key: ${{ runner.os }}-sonar
#          restore-keys: ${{ runner.os }}-sonar
#      - name: Info
#        run: mvn -version
#      - name: Build and analyze
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#        run: mvn -e --no-transfer-progress -Pscala-${{matrix.scala-version}} -Pspark-${{matrix.spark-version}} -Dgpg.skip=true -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=arangodb_arangodb-spark-datasource
