name: Java CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:

    timeout-minutes: 30
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        spark-version:
          - 2.4
          - 3.1
        topology:
          - single
          - cluster
        java-version:
          - 8
        docker-img:
          - docker.io/arangodb/arangodb:3.7.12

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: ${{matrix.java-version}}
          distribution: 'adopt'
      - name: Start Database
        run: ./docker/start_db_${{matrix.topology}}.sh ${{matrix.docker-img}}
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn -e --no-transfer-progress -Pspark-${{matrix.spark-version}} test
